version: '2'

services:
  seed:
    container_name: seed1
    hostname: seed
    image: hlavki/karaf-4-cellar
    volumes:
      - ./deploy:/opt/deploy
    environment:
      - SEED_HOST=seed
  member:
    container_name: member1
    hostname: member
    image: hlavki/karaf-4-cellar
    volumes:
      - ./deploy:/opt/deploy
    depends_on:
      - seed
    links:
      - seed
